@url = http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJzdWIiOiJlNDZiYTVlYS02Nzg4LTRjMzYtOTMxYy04MWM4M2NkY2FkZWMiLCJpYXQiOjE3NDk4NzI1NzcsImV4cCI6MTc0OTk1ODk3N30.5OOqzGoClLVqPM74nFU9x3MnhJXLaT2Xqa9CYt4fn6I


### Register
curl -X 'POST' \
  '{{url}}/auth/register' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "tedsds@hotmail.com",
  "password": "password13",
  "name": "John Doe"
}'

### Login
curl -X 'POST' \
  '{{url}}/auth/login' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "test@test.com",
  "password": "password123"
}'

### Get user by id
curl -X 'GET' \
  '{{url}}/auth/profile' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {{token}}'


### Get all spaces
curl -X 'GET' \
  '{{url}}/spaces' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {{token}}'

### Get space by id

curl -X 'GET' \
  '{{url}}/spaces/28e6bc6b-f3d9-4f39-9f04-7fa3bc6e4c6c' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {{token}}'

### Realizar la reserva
curl -X 'POST' \
  '{{url}}/reservations' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {{token}}' \
  -H 'Content-Type: application/json' \
  -d '{
  "userId": "81507042-a751-43ae-991b-8a956d51ca11",
  "spaceId": "bbcd0b1c-71c6-4b4c-9aa6-d5eaa0176449",
  "startTime": "2027-06-14T10:00:00Z",
  "endTime": "2027-06-14T11:00:00Z",
  "notes": "Reserva de prueba"
}
'

### Get all reservations
curl -X 'GET' \
  '{{url}}/reservations' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {{token}}'